//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.31 at 12:49:25 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:com:tradedoubler:pf:model:xml:common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.abc.affiliate.dataadapter.dto.product;
